development:
  API_AI_CLIENT_ACCESS_TOKEN: '513774acd00a49599a2028e28714ed65'
  ACCESS_TOKEN: 'EAAZATSh70ZADkBAMrAkbKEkioxuWJc8TpcHCaYaWYT7xUQH5yma5sELhtmQify9VF0l65SBFU6ZC5aNsETea966ZBd20uOl1DGG7wTSg8SWCrZBCdFVtFqt7pxUp2s5aKRBuZA5NnVWjq8DKsKWhtKihCARNUlYNNOLERfwiSSZCgZDZD'
  VERIFY_TOKEN: 'duc4nh'
  APP_SECRET: 'b6b0c19a7d8809d307f5680fa6b2d0cf'
  WEATHER_API_KEYREF: '781CF461BB6606AD814EFA58445F9F5F5B033976558B4904'

production:
  API_AI_CLIENT_ACCESS_TOKEN: '513774acd00a49599a2028e28714ed65'
  ACCESS_TOKEN: 'EAAZATSh70ZADkBAMrAkbKEkioxuWJc8TpcHCaYaWYT7xUQH5yma5sELhtmQify9VF0l65SBFU6ZC5aNsETea966ZBd20uOl1DGG7wTSg8SWCrZBCdFVtFqt7pxUp2s5aKRBuZA5NnVWjq8DKsKWhtKihCARNUlYNNOLERfwiSSZCgZDZD'
  VERIFY_TOKEN: 'duc4nh'
  APP_SECRET: 'b6b0c19a7d8809d307f5680fa6b2d0cf'
  WEATHER_API_KEYREF: '781CF461BB6606AD814EFA58445F9F5F5B033976558B4904'