# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# paypal_username:  'jml_api1.jmldirect.com.sg'
# paypal_password:  'EUUVV722SN6AFQYQ'
# paypal_signature: 'AOQ5TzljWsorn.7YTantIN5rTTeFARc6MHeeYTH9vwnuCxb7q6S9-DaK'


development:
  server_access_token: 'PJGG6O5I3X2XAMKNYHDQPSYRIGK2DJBX'
  ACCESS_TOKEN: 'EAAZATSh70ZADkBAMrAkbKEkioxuWJc8TpcHCaYaWYT7xUQH5yma5sELhtmQify9VF0l65SBFU6ZC5aNsETea966ZBd20uOl1DGG7wTSg8SWCrZBCdFVtFqt7pxUp2s5aKRBuZA5NnVWjq8DKsKWhtKihCARNUlYNNOLERfwiSSZCgZDZD'
  VERIFY_TOKEN: 'duc4nh'
  APP_SECRET: 'b6b0c19a7d8809d307f5680fa6b2d0cf'
  WEATHER_API_KEYREF: '781CF461BB6606AD814EFA58445F9F5F5B033976558B4904'

production:
  server_access_token: 'PJGG6O5I3X2XAMKNYHDQPSYRIGK2DJBX'
  ACCESS_TOKEN: 'EAAZATSh70ZADkBAMrAkbKEkioxuWJc8TpcHCaYaWYT7xUQH5yma5sELhtmQify9VF0l65SBFU6ZC5aNsETea966ZBd20uOl1DGG7wTSg8SWCrZBCdFVtFqt7pxUp2s5aKRBuZA5NnVWjq8DKsKWhtKihCARNUlYNNOLERfwiSSZCgZDZD'
  VERIFY_TOKEN: 'duc4nh'
  APP_SECRET: 'b6b0c19a7d8809d307f5680fa6b2d0cf'
  WEATHER_API_KEYREF: '781CF461BB6606AD814EFA58445F9F5F5B033976558B4904'