# production:
#   clients:
#     default:
#       database: heroku_6bf76c3s
#       hosts:
#         - ds151078.mlab.com:51078
#       options:
#         user: rth
#         password: 123456
#         roles:
#           - 'dbOwner'
#         max_pool_size: 20
#         min_pool_size: 2
production:
  clients:
    default:
      database: wbot_production
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 20
        min_pool_size: 2
development:
  clients:
    default:
      database: wbot_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: wbot_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
